spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    com.user.service: DEBUG
    zipkin2.reporter: DEBUG
    io.micrometer.tracing.export: DEBUG

